### PR TITLE
Added support for float images and others, ver. 2

### PR DESCRIPTION
**Pull request by ivokabel**
I removed the FreeImage library and my MS VS solution as you suggested and tested using CMake. Everything works just fine when you feed CMake with proper FreeImage paths.

I also tested it on my Ubuntu 14.04 virtual machine and improved it, so it compiles well (activated C+11 support and replaced some security versions of functions which are not supported by <cstdio> by default). Now it works well on my Linux too.

Additionally, I added a few more bugfixes and minor improvements.

### CODE REVIEW

**Comment by hectorgon** [comment]
Looks good! Merging

**Comment by ivokabel** [comment]
Great, thanks!

**Comment by hectorgon** [comment]
I haven't figured out the distribution process on github though, I didn't do the Debian packaging and the person who did it on sourceforge doesn't seem to have a visible github account.

**Comment by ivokabel** [comment]
I must admit that Linux packaging is a complete unknown to me. Isn't it possible to contact the person on sourceforge and ask him to have look at it here?

**Comment by hectorgon** [comment]
Yeah I will email him and see if he is on github

**Comment by ivokabel** [comment]
Any sign of life from the guy?

**Comment by hectorgon** [comment]
Sorry was preparing a big repo for open sourcing haven't gotten in
touch with Jeff Breidenbach I think he does the updates but he doesn't have
a git link. Closest I got was looking at this git submits here:

https://github.com/google/linear-book-scanner/commits/master

On Sat, Jun 6, 2015 at 3:15 PM, ivokabel notifications@github.com wrote:

> Any sign of life from the guy?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hectorgon/perceptual-diff/pull/2#issuecomment-109654267
> .

## 

Yee Yang Li Hector http://google.com/+HectorYee
_google.com/+HectorYee http://google.com/+HectorYee_

**Comment by ivokabel** [comment]
That's OK, I know how it feels like to be busy :)
I can try to contact him if you don't mind.

**Comment by hectorgon** [comment]
Sure please do!

**Comment by hectorgon** [comment]
I think there is a contact link here for the current maintainers

http://packages.ubuntu.com/trusty/perceptualdiff

**Comment by ivokabel** [comment]
I finally got to sending him an e-mail (...@debian.org). I was a little bit too busy to do that earlier...

**Comment by hectorgon** [comment]
Thanks!

**Pull request merged**
